apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "futtertrog.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
data:

  {{- if .Values.services.gitlab.enabled}}
  LOGIN_WITH_GITLAB: {{ .Values.services.gitlab.enabled | quote }}
  GITLAB_URL: {{ .Values.services.gitlab.url | quote }}
  GITLAB_CLIENT_ID: {{ .Values.services.gitlab.clientId | quote }}
  {{- end }}

  {{- if .Values.mealProviders.holzke.enabled}}
  HOLZKE_LOGIN: {{ .Values.mealProviders.holzke.login | quote }}
  HOLZKE_SCHEDULE: {{ .Values.mealProviders.holzke.cronjob | quote }}
  HOLZKE_ORDER_INFO: {{ .Values.mealProviders.holzke.orderInfo | quote }}
  {{- end }}

  NEXMO_KEY: {{ .Values.services.nexmo.key | quote }}

  CALL_A_PIZZA_LOCATION: {{ .Values.mealProviders.call_a_pizza.location | quote }}
  CALL_A_PIZZA_CATEGORIES: {{ .Values.mealProviders.call_a_pizza.categories | toJson | quote }}

  FLASCHENPOST_ZIPCODE: {{ .Values.mealProviders.flaschenpost.zipcode | quote }}
  FLASCHENPOST_CATEGORIES: {{ .Values.mealProviders.flaschenpost.categories | toJson | quote }}

  MAIL_DRIVER: {{ .Values.mail.driver | quote }}

  {{- if .Values.mail.host }}
  MAIL_HOST: {{ .Values.mail.host | quote }}
  {{- end }}

  {{- if .Values.mail.port}}
  MAIL_PORT: {{ .Values.mail.port | quote }}
  {{- end }}

  {{- if .Values.mail.username}}
  MAIL_USERNAME: {{ .Values.mail.username | quote }}
  {{- end }}

  {{- if .Values.mail.encryption }}
  MAIL_ENCRYPTION: {{ .Values.mail.encryption | quote }}
  {{- end }}

  {{- if .Values.services.vapid.public_key }}
  VAPID_PUBLIC_KEY: {{ .Values.services.vapid.public_key | quote }}
  {{- end }}