apiVersion: v1
kind: Secret
metadata:
  name: {{ include "futtertrog.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
type: Opaque
data:
  {{- if .Values.appKey }}
  APP_KEY: {{ .Values.appKey | b64enc | quote }}
  {{- else }}
  APP_KEY: {{ randAlphaNum 16 | b64enc  | quote }}
  {{- end }}

  DATABASE_URL: {{ include "futtertrog.databaseUrl" . | b64enc  | quote }}

  {{- if .Values.mealProviders.holzke.password }}
  HOLZKE_PASSWORD: {{ .Values.mealProviders.holzke.password | b64enc  | quote }}
  {{- end }}

  {{- if .Values.services.nexmo.secret }}
  NEXMO_SECRET: {{ .Values.services.nexmo.secret | b64enc  | quote }}
  {{- end }}

  {{- if .Values.services.gitlab.clientSecret }}
  GITLAB_CLIENT_SECRET: {{ .Values.services.gitlab.clientSecret | b64enc  | quote }}
  {{- end }}

  {{- if .Values.mail.password }}
  MAIL_PASSWORD: {{ .Values.mail.password | b64enc  | quote }}
  {{- end }}

  {{- if .Values.services.vapid.private_key }}
  VAPID_PRIVATE_KEY: {{ .Values.services.vapid.private_key | b64enc  | quote }}
  {{- end }}