apiVersion: v2
name: unpubd
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "0.0.5"

dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 13.x.x
    condition: mongodb.enabled
