{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kimai2.name" . }}-secret
  labels:
    {{- include "kimai2.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMINPASS: {{ .Values.kimaiAdminPassword }}
  APP_SECRET: {{ .Values.kimaiAppSecret }}
  DATABASE_URL: {{ include "kimai2.databaseUrl" . }}
  MAILER_URL: {{ .Values.kimaiMailerUrl }}
{{- end -}}
