apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  APP_ENV: {{ .Values.shopware.appEnv | quote }}
  APP_URL: {{ .Values.shopware.appUrl | quote }}
  DATABASE_HOST: {{ include "shopware.databaseHost" . | quote }}
  SHOPWARE_ES_HOSTS: {{ .Values.shopware.elasticSearch.hosts | quote }}
  SHOPWARE_ES_ENABLED: {{ .Values.shopware.elasticSearch.enabled | quote }}
  SHOPWARE_ES_INDEXING_ENABLED: {{ .Values.shopware.elasticSearch.indexingEnabled | quote }}
  SHOPWARE_ES_INDEX_PREFIX: {{ .Values.shopware.elasticSearch.indexPrefix | quote }}
  SHOPWARE_HTTP_CACHE_ENABLED: {{ .Values.shopware.httpCache.enabled | quote }}
  SHOPWARE_HTTP_DEFAULT_TTL: {{ .Values.shopware.httpCache.defaultTtl | quote }}
  DISABLE_ADMIN_WORKER: {{ .Values.shopware.admin.disableWorker | quote }}
  INSTALL_LOCALE: {{ .Values.shopware.install.locale | quote }}
  INSTALL_CURRENCY: {{ .Values.shopware.install.currency | quote }}
  INSTALL_ADMIN_USERNAME: {{ .Values.shopware.install.adminUsername | quote }}
  INSTALL_ADMIN_PASSWORD: {{ .Values.shopware.install.adminPassword | quote }}
  CACHE_ADAPTER: {{ .Values.shopware.cache.adapter | quote }}
  REDIS_CACHE_HOST: {{ .Values.shopware.cache.host | quote }}
  REDIS_CACHE_PORT: {{ .Values.shopware.cache.port | quote }}
  REDIS_CACHE_DATABASE: {{ .Values.shopware.cache.database | quote }}
  SESSION_ADAPTER: {{ .Values.shopware.session.adapter | quote }}
  REDIS_SESSION_HOST: {{ .Values.shopware.session.host | quote }}
  REDIS_SESSION_PORT: {{ .Values.shopware.session.port | quote }}
  REDIS_SESSION_DATABASE: {{ .Values.shopware.session.database | quote }}
  {{- if .Values.shopware.activePlugins }}
  ACTIVE_PLUGINS: {{ .Values.shopware.activePlugins | quote }}
  {{- end }}
  TZ: {{ .Values.shopware.php.timeZone | quote }}
  PHP_MAX_UPLOAD_SIZE: {{ .Values.shopware.php.maxUploadSize | quote }}
  PHP_MAX_EXECUTION_TIME: {{ .Values.shopware.php.maxExecutionTime | quote }}
  PHP_MEMORY_LIMIT: {{ .Values.shopware.php.memoryLimit | quote }}
  FPM_PM: {{ .Values.shopware.php.fpm.pm | quote }}
  FPM_PM_MAX_CHILDREN: {{ .Values.shopware.php.fpm.maxChildren | quote }}
  FPM_PM_START_SERVERS: {{ .Values.shopware.php.fpm.startServers | quote }}
  FPM_PM_MIN_SPARE_SERVERS: {{ .Values.shopware.php.fpm.minSpareServers | quote }}
  FPM_PM_MAX_SPARE_SERVERS: {{ .Values.shopware.php.fpm.maxSpareServers | quote }}